eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /health
    healthCheckUrlPath: /health
server:
  port: 8762
spring:
  application:
    name: eureka-server-hi